version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: postgress_paswordgen
    #restart: always
#
    environment:
#      - POSTGRES_USER=adminka
#      - POSTGRES_PASSWORD=kirka2906
#      - POSTGRES_NAME=db
      PGDATA: /var/lib/postgresql/data/db/
      POSTGRES_PASSWORD: kirka2906
      POSTGRES_USER: adminka
      POSTGRES_DB: db

    volumes:
      - postgres:/var/lib/postgresql/data/

  web:
    build: .
    container_name: web_password_gen
    #restart: always
    command: >
      sh -c " 
      python manage.py wait_for_bd &&
      python manage.py migrate &&
      python manage.py upgrade_sites &&
      python manage.py collectstatic &&
      python manage.py runserver 0.0.0.0:8000 "

    expose:
      - 8000

    environment:

      - DEBUG=1

    depends_on:
      - db


  nginx:
    image: nginx

    container_name: nginx
    volumes:
    - ./hosts:/etc/nginx/
    - ./logs/:/etc/nginx/logs/
    ports:
    - "80:80"

    depends_on:
      - web
volumes:
  postgres :
  nginx.conf: